In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
from util import sidewalk_qualifer
from extract_direct_indicators import *

In [5]:
dir_ind = extract_direct_indicators(sidewalk_qualifer, 'chi')
dir_ind

,id,nversions,nusers,nedits,ntags,dir_confirmations,nrollbacks,visibility,type
0,23946552,4,4,5,4,2,0,B,W
1,23946708,16,7,10,4,3,1,B,W
2,23946710,7,6,7,5,4,1,B,W
3,23946711,10,5,4,4,2,0,B,W
4,23946714,6,4,8,5,3,0,B,W
...,...,...,...,...,...,...,...,...,...
18816,1084359906,1,1,0,2,0,0,B,W
18817,1084359907,1,1,0,2,0,0,B,W
18818,1084359909,1,1,0,2,0,0,B,W
18819,1084362117,1,1,0,2,0,0,B,W
18820,1084362118,1,1,0,2,0,0,B,W

In [8]:
stats = get_stats(dir_ind)
stats

      nversions    nusers    nedits     ntags  dir_confirmations  nrollbacks
mean   1.569258  1.333298  0.233728  2.154827           0.047022    0.003454
25%    1.000000  1.000000  0.000000  2.000000           0.000000    0.000000
50%    1.000000  1.000000  0.000000  2.000000           0.000000    0.000000

In [ ]:
# To measure trustworthiness of sidewalk data: dir/indir indicators of the *road* that is associated with that sidewalk!

# Two steps:

# Check if sidewalk-data availabile or not. Four cases:
    # i) Partial availability: sidewalk geometry available but tag is not available on the associated road
    # ii) Partial availability: sidewalk geometry not availble, but sidewalk tag (yes/ left/ right/ both) is on the road
    # iii) Full availibility: Both sidewalk geometry and sidewalk tag on the associated road are available
    # iv) Unavailable: Neither geometry nor the tag of associated road is available

# if available, check if the associated road data is trustworthy or not

# Indirect and time indicator measurable